### ISSUE TITLE
Does not show random gifs

### ISSUE THREAD

**Issue by nidazehraa** [MQasimSarfraz/moodboard#2]

**Comment by mqasimsarfraz** [comment]
Thanks for trying the out `moodboard`. We added the support of random gifs couple of days back, https://github.com/MQasimSarfraz/moodboard/commit/428dee176c60b15c3c3cb0ff139a967c21a69579 . Is this is what you are looking for?

**Comment by mqasimsarfraz** [comment]
The issue was fixed in the current release!
